apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinout
  namespace: pinout
  labels:
    app: pinout
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pinout
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pinout
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: pinout-envs
        image: swr.tr-west-1.myhuaweicloud.com/t3vakfi-cce/pinout
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - sleep 5
        name: pinout
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
